version: "3"

services:
    api:
        container_name: api_node
        build:
            context: ./
            dockerfile: ./docker/api/transpile/Dockerfile
        ports:
            - 80:63000
        env_file:
            - .env.development