version: "3"

services:
    api:
        container_name: api_node
        build:
            context: ./
            dockerfile: ./docker/api/Dockerfile
        ports:
            - 80:63000
        volumes:
            - .:/usr/src/app
        env_file:
            - .env.development